<?php
session_start();
include_once __DIR__ . '/../_env/define.php';
include_once __DIR__ . '/config/site.php';
include_once __DIR__ . '/config/user.php';
include_once __DIR__ . '/config/page.php';
include_once __DIR__ . '/config/status.php';
include_once __DIR__ . '/config/session.php';
include_once __DIR__ . '/config/database.php';
include_once __DIR__ . '/config/funeral.php';
include_once __DIR__ . '/func/array.php';
include_once __DIR__ . '/func/database.php';
include_once __DIR__ . '/func/string.php';
include_once __DIR__ . '/func/calc.php';
include_once __DIR__ . '/func/editfile.php';
include_once __DIR__ . '/func/pager.php';
include_once __DIR__ . '/func/path.php';
include_once __DIR__ . '/func/session.php';
include_once __DIR__ . '/func/minify.php';
include_once __DIR__ . '/database/funeral.php';
include_once __DIR__ . '/database/funeral_client.php';
include_once __DIR__ . '/database/container_cs.php';
include_once __DIR__ . '/database/report.php';
include_once __DIR__ . '/library/_module/editsql.php';
include_once __DIR__ . '/library/_module/disp.php';
include_once __DIR__ . '/library/_module/dataformat.php';
include_once __DIR__ . '/library/crm/class.php';
include_once __DIR__ . '/routes/web.php';

$_SESSION = appFuncSession::checkLogout($_SESSION, $_POST);
appFuncSession::redirect(appRoutesWeb::sitemap['login']['path']);